# Generated by Django 2.0.13 on 2019-05-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190511_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileuser',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profileuser',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
